apiVersion: v1

kind: ConfigMap

metadata:
  name: "{{ .Release.Name }}-container-hooks-configmap"

data:

  # This hook accepts an optional destination path, copying the files from the import source
  # (/var/hvmail/control.import) into that destination (default: /var/hvmail/control).
  import_control_files: |
    #!/bin/bash

    src="/var/hvmail/control.import"

    if [ -n "$1" ]; then
      dst="$1"
    else
      dst="/var/hvmail/control"
    fi

    if [ ! -d "$src" ]; then
      echo "Source path $src is not a directory."
      exit 1
    fi

    if [ ! -d "$dst" ]; then
      echo "Destination path $dst is not a directory."
      exit 1
    fi

    rsync --archive --quiet --copy-links "$src"/ "$dst"/

  # This hook runs during shutdown and drains its pod of messages.
  pre_shutdown_hook: |
    #!/bin/bash

    {{ $loadBalancer := (printf "%s-mta-service" .Release.Name) -}}

    date > /var/lib/greenarrow/message_drain.start_time.txt

    {{ if empty .Values.drainFallbackVolumeClaim -}}
    /var/hvmail/bin/greenarrow service drain \
      {{ $loadBalancer | quote }} \
      2>&1 | tee -a /var/lib/greenarrow/message_drain.log
    {{ else -}}
    /var/hvmail/bin/greenarrow service drain \
      --fallback-path=/mnt/greenarrow-fallback \
      --automatic-fallback-after={{ printf "%ds" (int64 .Values.mtaDrainFallbackAfterSeconds) | quote }} \
      {{ $loadBalancer | quote }} \
      2>&1 | tee -a /var/lib/greenarrow/message_drain.log
    {{- end }}

    drainExitStatus=$?

    date > /var/lib/greenarrow/message_drain.end_time.txt

    echo "Drain exited status $drainExitStatus."

    if [[ $drainExitStatus -ne 0 ]]; then
      {{ if not (empty .Values.drainFallbackVolumeClaim) -}}
      # We have a fallback path, take a snapshot of our persistent path now.
      /var/hvmail/libexec/svc_make_state down 30 2 /service/*
      mkdir -p /mnt/greenarrow-fallback/failed_drain_instances
      cd /mnt/greenarrow-fallback/failed_drain_instances
      hostname=`hostname`
      snapshot="`pwd`/$hostname.tar.gz"
      tar czf "$snapshot" -C /var/lib/greenarrow --transform "s,^.,$hostname," --warning=no-file-ignored .
      echo "Snapshot saved to $snapshot."
      {{- end }}
    fi

    exit $drainExitStatus
