apiVersion: v1

kind: Service

metadata:
  name: {{ .Release.Name }}-mta-service
  labels:
    app: {{ .Release.Name }}
    role: mta

spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
    role: mta
  ports:
    - name: smtp1
      protocol: TCP
      port: 25
      targetPort: 25
    - name: smtp2
      protocol: TCP
      port: 587
      targetPort: 587
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
