apiVersion: v1

kind: Secret

metadata:
  name: {{ .Release.Name }}-secret

type: Opaque

data:
  secret_constant1: {{ println (substr 0 32 .Values.secretConstant) | b64enc | quote }}
  secret_constant2: {{ println (substr 32 64 .Values.secretConstant) | b64enc | quote }}
